# Example of verifying a sinlge ONNX model with multiple VNNLIB specifications in a csv file (data are defined in VNNLIB).
general:
  root_path: /home/guanqizh/Data/oopsla25supplements/vnncomp2021/benchmarks/mnistfc  # Root path of the csv file.
  csv_name: /home/guanqizh/Data/oopsla25supplements/vnncomp2021/benchmarks/mnistfc/mnistL2_instances.csv  # Name of the csv file (ONLY one column listed paths to vnnlibs).
model:
  # Assuming you have cloned the vnncomp2021 repository: https://github.com/stanleybak/vnncomp2021
  onnx_path: /home/guanqizh/Data/oopsla25supplements/vnncomp2021/benchmarks/mnistfc/mnist-net_256x2.onnx  # Path to ONNX model.
  input_shape: [ -1, 1, 28, 28 ]  # The vnnlib does not have input shape information, user should specify here.
solver:
  batch_size: 1  # Number of subdomains to compute in parallel in bound solver. Decrease if you run out of memory.
bab:
  timeout: 120  # Timeout threshold for branch and bound. Increase for verifying more points.
  branching:  # Parameters for branching heuristics.
    reduceop: min  # Reduction function for the branching heuristic scores, min or max. Using max can be better on some models.
    method: kfsb  # babsr is fast but less accurate; fsb is slow but most accurate; kfsb is usually a balance.
    candidates: 3  # Number of candidates to consider in fsb and kfsb. More leads to slower but better branching. 3 is typically good enough.
attack:
  pgd_order: skip
