general:
  enable_incomplete_verification: False
model:
  name: mnist_cnn_4layer
  path: /home/guanqizh/Data/oopsla25supplements/vnncomp2021/benchmarks/mnistfc/mnist-net_256x4.onnx
data:
  dataset: MNIST_SAMPLE
specification:
  epsilon: 0.3
  robustness_type: runnerup
attack:
  pgd_order: skip
solver:
  batch_size: 300
  beta-crown:
    iteration: 20
bab:
  timeout: 180
  decision_thresh: .inf
  branching:
    reduceop: max
